config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  devise_for :admins

  root "main#index"

  resources :courses,     only: [:index, :show]
  resource  :cart,        only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get  '/cart/checkout', to: 'carts#checkout'
  post '/cart/checkout', to: 'carts#checkout', as: :checkout
  post '/cart/create_user', to: 'carts#create_user', as: :checkout_user_create
  get  '/cart/place_order', to: 'carts#place_order', as: :place_order

  namespace :education do
    resources :courses, only: [:show] do
      member do
        get 'show_lesson'
      end
    end
  end

  namespace :admin do
    root "main#index"

    resources :courses
    resources :course_modules
    resources :lessons
    resources :teachers
    resources :categories
    resources :users
    resources :articles
    resources :orders
    resources :videos
    resources :tasks
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_taggable

  has_attached_file :main_img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :main_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/cooking_task.rb
class CookingTask < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_modules
  has_many :lessons
  has_many :comments
  has_many :order_items

  has_and_belongs_to_many :teachers

  belongs_to :category

  has_attached_file :cover_photo, styles: { medium: "800x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\z/

  has_attached_file :avatar, styles: { medium: "800x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/course_module.rb
class CourseModule < ApplicationRecord
  belongs_to :course

  has_many :lessons
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  belongs_to :course_module

  has_many :photos
  has_many :videos
  has_many :student_photos
  has_many :tasks

  accepts_nested_attributes_for :photos, allow_destroy: true

  has_attached_file :pdf
  validates_attachment :pdf, :content_type => { :content_type => %w(application/pdf) }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_items

  # before_create :set_order_status
  # before_save :update_total

  # def total
  #   order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  # end

  private

  # def set_order_status
  #   self.order_status_id = 1
  # end
  #
  # def update_total
  #   self[:total] = total
  # end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :course
  belongs_to :order

  # validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # validate  :course_present
  # validate  :order_present

  # before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      course.price
    end
  end

  def total_price
    unit_price
  end

  private

  def course_present
    if course.nil?
      errors.add(:course, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :lesson

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/student_photo.rb
class StudentPhoto < ApplicationRecord
  belongs_to :lesson
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :lesson
  has_many :cooking_tasks
  has_many :users, through: :cooking_tasks
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :courses

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_many :comments

  has_many :cooking_tasks
  has_many :tasks, through: :cooking_tasks

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
  
  has_many :order_items
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.all.order("created_at DESC").includes(:lesson)
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def new
    @video = Video.new

    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to(admin_videos_url, notice: 'Video was successfully created.') }
      else
        @videos = Video.all
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update_attributes(video_params)

        format.html { redirect_to(admin_videos_url, notice: 'Video was successfully updated.') }
      else
        @videos = Video.all
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(admin_videos_url) }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:url, :embed_code, :price, :lesson_id)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception
  layout 'admin'
  before_action :authenticate_admin!

  def authenticate_admin!
    if current_admin.nil?
      redirect_to new_admin_session_path, alert: "Not authorized"
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	
  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/videos/_form.html.erb
<%= simple_form_for [:admin, @video] do |f| %>
  <%= f.input :url, input_html: { class: "admin_form_input" }, wrapper_html: { class: 'admin_form_input_container' } %>

  <%= f.input :embed_code, input_html: { class: "admin_form_input textarea" }, wrapper_html: { class: 'admin_form_input_container' } %>

  <%= f.input :price, input_html: { class: "admin_form_input" }, wrapper_html: { class: 'admin_form_input_container' } %>

  <%= f.association :lesson, prompt: "Choose a lesson", wrapper_html: { class: 'admin_form_input_container' } %>

  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/admin/videos/edit.html.erb
<section>
  <div class="container">
    <div class="col-sm-12 admin_form_heading">
      Editing Video
    </div>

    <div class="col-sm-12 admin_form_heading">
      <%= render 'form' %>
    </div>

    <div class="col-sm-12 admin_form_heading">
      <%= link_to 'Back', admin_videos_path %>
    </div>
  </div>
</section>

app/views/admin/videos/index.html.erb
<section>
  <div class="container">
    <div class="col-sm-12 admin_form_heading">
      Videos
    </div>

    <div class="col-sm-12">
      <p id="notice"><%= notice %></p>

      <table class="table admin_table">
        <thead>
          <tr>
            <th>
              Url
            </th>

            <th>
              Code
            </th>

            <th>
              Price
            </th>

            <th>
              Lesson
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <% @videos.each do |video| %>
            <tr>
              <td>
                <%= link_to "Video Link", video.url %>
              </td>

              <td>
                <%= video.embed_code.html_safe %>
              </td>

              <td>
                <%= video.price %>
              </td>

              <td>
                <%= video.lesson.name %>
              </td>

              <td>
                <%= link_to 'Show', admin_video_path(video) %>

                <%= link_to 'Edit', edit_admin_video_path(video) %>

                <%= link_to 'Destroy', admin_video_path(video), method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Video', new_admin_video_path %>
    </div>
  </div>
</section>

app/views/admin/videos/new.html.erb
<section>
  <div class="container">
    <div class="col-sm-12 admin_form_heading">
      New Video
    </div>

    <div class="col-sm-12">
      <%= render 'form' %>
    </div>

    <div class="col-sm-12 admin_form_heading">
      <%= link_to 'Back', admin_videos_path %>
    </div>
  </div>
</section>